export const TW_CLASS = {
  // ' disabled:opacity-50 disabled:shadow-none disabled:cursor-not-allowed',

  BTN: 'cursor-pointer flex justify-center items-center border align-middle font-sans font-medium text-center select-none transition-all duration-300 ease-in text-sm px-4 py-2 rounded-lg shadow-sm hover:shadow-md focus:ring-2 focus:outline-none focus:shadow-none data-[shape=pill]:rounded-full data-[width=full]:w-full',
  BTN_SIMPLE: 'bg-blue-600 border-blue-600 text-blue-50 hover:bg-blue-800 hover:border-blue-800 focus:ring-blue-300',
  BTN_PRIMARY: 'text-white bg-blue-600 border border-none hover:bg-blue-700 hover:text-white focus:ring-blue-300 active:bg-primary-700',
  BTN_SECONDARY: 'flex items-center justify-center border text-gray-900 border-gray-300 bg-white hover:bg-gray-100 hover:text-blue-700 hover:border-gray-300 focus:ring-gray-100 focus:z-10 active:bg-gray-100 active:text-white',
  BTN_ACCENT: 'flex items-center justify-center text-blue-700 border border-transparent bg-blue-50 hover:bg-blue-100 focus:ring-blue-100 active:bg-primary-100 disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none',
  BTN_GREEN: 'flex items-center justify-center transition-all border text-white bg-green-700 hover:bg-green-800 focus:bg-success-600 focus:ring-green-300 active:bg-success-700 disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none',
  BTN_YELLOW: 'flex items-center justify-center transition-all border border-warning-500 text-white bg-yellow-600 hover:bg-yellow-700 focus:bg-warning-700 focus:ring-yellow-300 active:bg-warning-700 disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none',
  BTN_RED: 'flex items-center justify-center transition-all border border-red-500 text-white bg-red-700 hover:bg-red-800 focus:bg-red-700 focus:ring-red-300 active:bg-red-700 disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none',
  BTN_PURPLE: 'flex items-center justify-center transition-all border border-purple-500 text-white bg-purple-700 hover:bg-purple-800 focus:bg-purple-700 focus:ring-purple-300 active:bg-purple-700 disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none',
  BTN_INDIGO: 'flex items-center justify-center transition-all border border-indigo-500 text-white bg-indigo-700 hover:bg-indigo-800 focus:bg-indigo-700 focus:ring-indigo-300 active:bg-indigo-700 disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none',
  BTN_PINK: 'flex items-center justify-center transition-all border border-pink-500 text-white bg-pink-500 hover:bg-pink-600 focus:bg-pink-700 focus:ring-pink-200 active:bg-pink-700 disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none',
  BTN_CIRCLE: '!p-2.5 !rounded-full min-w-[40px] inline-flex justify-center items-center gap-x-2 disabled:pointer-events-none',

  // '          disabled:opacity-50 disabled:cursor-not-allowed   ',

  BTN_GHOST: 'py-2.5 px-4 text-blue-800 bg-transparent border-transparent !shadow-none hover:bg-blue-700/5 hover:border-blue-700/5 hover:shadow-none focus:ring-blue-300 focus:border-gray-800 transition-all disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none data-[shape=pill]:rounded-full data-[width=full]:w-full',
  BTN_DISABLED: 'text-white bg-primary-400 cursor-not-allowed font-medium rounded-lg text-center',
  BTN_BLOCK: 'w-full',
  BTN_SIZE_XS: '!py-2 !px-3 !text-xs',
  BTN_SIZE_SM: '!py-2 !px-3 !text-sm',
  BTN_SIZE_LG: '!px-5 !py-3 !text-base',
  BTN_SIZE_XL: '!px-6 !py-3.5 !text-base',
  BTN_ICON_XS: 'p-2 flex items-center',
  BTN_ICON_SM: 'p-2 flex items-center',
  BTN_ICON: 'inline-flex items-center justify-between',
  BTN_ICON_LG: 'p-4 flex items-center',
  BTN_ICON_ONLY: '!p-2.5 flex items-center transition-all disabled:pointer-events-none disabled:opacity-50 border-0',
  BTN_ICON_LOADING: 'animate-spin inline-block border-3 border-t-transparent rounded-full',
  BTN_GROUP_LEFT: 'px-4 py-2 text-sm text-center transition-all border border-r-0 rounded-md rounded-r-none shadow-sm border-gray-300 disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none',
  BTN_GROUP_MIDDLE: 'px-4 py-2 text-sm text-center transition-all border rounded-md rounded-l-none rounded-r-none shadow-sm border-gray-300 disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none',
  BTN_GROUP_RIGHT: 'px-4 py-2 text-sm text-center transition-all border border-l-0 rounded-md rounded-l-none shadow-sm border-gray-300 disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none',
  BTN_LINK: 'flex items-center justify-center text-sm font-medium bg-transparent hover:bg-transparent focus:ring-0 focus:ring-gray-200 text-blue-600 no-underline hover:text-primary-700 active:underline hover:underline',

  BTN_A: 'group relative overflow-hidden focus:ring-4 inline-flex items-center rounded-lg justify-center',
  BTN_A_TYPE_A: 'px-5 py-2.5',
  BTN_A_TYPE_B: 'px-7 py-2.5',
  BTN_A_SIMPLE: 'bg-blue-600 focus:ring-blue-300 text-white',
  BTN_A_PRIMARY: 'bg-blue-700 focus:ring-blue-300 text-white',
  BTN_A_SECONDARY: 'bg-white focus:ring-gray-100 text-gray-900 hover:bg-gray-100 hover:text-blue-700 active:bg-gray-100 active:text-white',
  BTN_A_ACCENT: 'bg-blue-50 focus:ring-blue-100 text-blue-700 hover:bg-blue-100 active:bg-primary-100',
  BTN_A_GREEN: 'bg-green-700 focus:ring-green-300 text-white',
  BTN_A_YELLOW: 'bg-yellow-600 focus:ring-yellow-300 text-white',
  BTN_A_RED: 'bg-red-700 focus:ring-red-300 text-white',
  BTN_A_PURPLE: 'bg-purple-700 focus:ring-purple-300 text-white',
  BTN_A_INDIGO: 'bg-indigo-700 focus:ring-indigo-300 text-white',
  BTN_A_PINK: 'bg-pink-500 focus:ring-pink-200 text-white',
  BTN_A_GHOST: 'bg-white focus:ring-blue-300 text-gray-600 transition-all hover:text-white hover:bg-blue-600',
  BTN_A_DISABLED: 'bg-primary-400 text-white',

}
